# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-23 10:13
from __future__ import unicode_literals

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='image',
            field=models.ImageField(null=True, upload_to=api.models.photos_file_name),
        ),
    ]
