# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-23 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170623_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
