# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-23 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170623_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='text',
        ),
        migrations.AlterField(
            model_name='photos',
            name='name',
            field=models.TextField(),
        ),
    ]
